use  consumer_shopping_behavior;

select * from consumer_shopping_behavior.consumer;

-- 1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as total_revenue from consumer
group by gender;



-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from consumer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount)from consumer);



-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) as avg_review_rating from consumer
group by item_purchased
order by (avg_review_rating) desc
limit 5;



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amt from consumer
where shipping_type in ('Standard','Express')
group by shipping_type;



-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customer,
sum(purchase_amount) as total_revenue,
avg(purchase_amount) as avg_spent from consumer 
group by subscription_status
order by total_revenue,avg_spent;



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM consumer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM consumer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;



-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM consumer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from consumer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as total_revenue from consumer
group by age_group
order by total_revenue desc;